name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify
      - name: Commit build artifacts (dist, devdist, docs, coverage)
        # Only run on main branch push (e.g. pull request merge). 
        # Don't run again on an already pushed auto commit.
        if: github.event_name == 'push' && env.is-auto-commit == false
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: Drip Files
          path: ./public
          retention-days: 21